### ISSUE TITLE
Not working on Github Actions

### ISSUE THREAD

**Issue by wongjiahau** [denosaurs/deno_brotli#2]
When my `main.ts` has the following content:
```ts
import { compress } from "https://deno.land/x/brotli@v0.1.3/mod.ts";
compress(new TextEncoder().encode("hi"))
```
When I run `deno run main.ts` in Github Actions, I will get this error:
```
error: No such file or directory (os error 2)
```

The image I'm using is`ubuntu-latest`, the Deno version I'm using is `1.0.5`

Seems like this is related to https://github.com/denosaurs/deno_brotli/runs/723112671

I think this is broken since Deno `1.0.3`, based on that Github job.

**Comment by eliassjogreen** [comment]
Yeah, we have had this problem with `deno test` on mac and linux since 1.0.3 and it has happened before. On windows it works fine. Probably a problem with either deno itself or the setup-deno github action dependency.

**Comment by wongjiahau** [comment]
@eliassjogreen have you raise this issue to Deno developer?

**Comment by eliassjogreen** [comment]
[deno#6057](https://github.com/denoland/deno/issues/6057)

**Comment by eliassjogreen** [comment]
@wongjiahau does this issue still persist or can I close this issue?
